good start for create tour page
umgc/spring2023 pull request #36
Opened 2023-03-03 05:28 UTC by CDovel

2023-03-05 17:07 UTC, tpbnick commented on virotour/lib/src/tour/tour_create_view.dart
> +// tour_edit_view.dart
remove

2023-03-05 17:08 UTC, tpbnick commented on virotour/lib/src/tour/tour_create_view.dart
> +                      //       title: const Text('Failed to update tour'),
Change to "Failed to create tour"

2023-03-05 17:08 UTC, tpbnick commented on virotour/lib/src/tour/tour_create_view.dart
> +                      //     'http://127.0.0.1:8081/api/update/tour/${widget.tour.id}';
Change to the create tour endpoint

2023-03-05 17:34 UTC, nguyendviet commented
- [ ] Merge https://github.com/umgc/spring2023/pull/33

2023-03-11 16:31 UTC, tpbnick commented
> * [x]  Merge [Hamburger menu #33](https://github.com/umgc/spring2023/pull/33) @menchukf Can you merge yours to unblock Christian?

Just merged.

2023-03-11 16:37 UTC, tpbnick commented
I linked up the `tour_create_view` with the hamburger menu.  @CDovel @nguyendviet

2023-03-12 01:54 UTC, nguyendviet commented
@CDovel Thank you for your work!

There are some issues with your code:
- [ ] It works on Chrome. I can select photos and remove them from the list. Can you make the Save button to go to the Tour page? In the future, it'll lead to the newly created tour. Please specify that in a comment. Once we click Save, it'll send all the images to the blob storage, wait for the response from the server and redirect to the Tour.
- [ ] It doesn't work on iOS due to
```
Exception has occurred.
PlatformException (PlatformException(invalid_image, Cannot load representation of type public.jpeg, NSItemProviderErrorDomain, null))
```
Error on [this line](https://github.com/umgc/spring2023/blob/acec1d2d34c3d4d1ee9c8406dfb08bf0d2cedfd0/virotour/lib/src/tour/tour_create_view.dart#L125).
<img width="999" alt="Screenshot 2023-03-11 at 20 50 01" src="https://user-images.githubusercontent.com/30057363/224519860-a5acfec9-a75a-4c4e-b49a-5bb5970c6ee4.png">
- [ ] It doesn't work on Android for a common error:
<img width="581" alt="Screenshot 2023-03-11 at 20 48 27" src="https://user-images.githubusercontent.com/30057363/224519881-b581f7d6-d79c-4534-aa8f-de1a21c1a401.png">
This is because on Android, a request needs a Header. You can Google/ChatGPT a solution.

2023-03-12 01:58 UTC, nguyendviet commented on virotour/test/widget_test.dart
> +    await tester.pumpWidget(const MyApp());
```suggestion
 testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    final settingsController = SettingsController(SettingsService());
    await tester.pumpWidget(App(
      settingsController: settingsController,
    ));
```

2023-03-12 01:58 UTC, nguyendviet commented on virotour/test/widget_test.dart
> +import 'package:virotour/main.dart';
```suggestion
import 'package:virotour/src/app.dart';
import 'package:virotour/src/settings/settings_controller.dart';
import 'package:virotour/src/settings/settings_service.dart';
```

2023-03-12 18:17 UTC, CDovel commented
@nguyendviet from what i've found online that problem with iOS seems to be either a corrupt image that you're trying to send or a bug with the iOS simulator. That library should be able to support iOS. The android problem I will make sure to add a header.

2023-03-12 23:35 UTC, CDovel commented
The header should be added now to work on android.

2023-03-15 16:35 UTC, nguyendviet requested changes
@CDovel Thank you for your work. Your feature works great on Chrome!

- I've rebased your branch and resolved all conflicts to save you some time.
- On Android, it has a margin error. It's a small one but it'll affect our demo. Can you fix it?
<img width="488" alt="Screenshot 2023-03-15 at 12 33 17" src="https://user-images.githubusercontent.com/30057363/225377741-539d51b5-937f-4c52-9b6a-fa15809d7676.png">

- On iOS, it throws an error. You'll need to fix this.
<img width="890" alt="Screenshot 2023-03-15 at 11 59 05" src="https://user-images.githubusercontent.com/30057363/225377831-7a1ef778-7f3e-4f57-839d-6cf28d761ad4.png">

2023-03-16 01:26 UTC, CDovel commented
Hey @nguyendviet my most recent commit should fix the android problem. I still need to look closer into the issues on iOS.

2023-03-16 02:00 UTC, nguyendviet commented
Unfortunately, it still doesn't work. Android has many screen sizes. I recommend you do something like [this](https://github.com/umgc/spring2023/blob/team_a_dev/virotour/lib/src/tour/tour_details_view.dart#L37-L42).
<img width="486" alt="Screenshot 2023-03-15 at 21 58 52" src="https://user-images.githubusercontent.com/30057363/225490313-ad6c91bf-3a03-491c-9c1a-8253c6b24259.png">

2023-03-19 18:44 UTC, nguyendviet approved these changes
I've checked it. Great work, Chris!

2023-03-19 22:59 UTC, merged